import NavBar from './components/NavBar'
import SharedFooter from './components/SharedFooter'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Try Next',
  description: 'Generated by create next app',
}

 const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
   
        <NavBar />
        {children}
       
        <SharedFooter />
        </body>
    </html>
  )
}

export default RootLayout;